### ISSUE TITLE
Can't open my Keepass2 database : The database key appears invalid or else the database is corrupt.

### ISSUE THREAD

**Issue by sebma** [alecsammon/kpcli#2] opened 2016-04-13 15:59 UTC
Hi,

I manage to open my database with both KeepassX and Keepass2 but not with kpcli:

```
kpcli:/> ver
2.4
kpcli:/> open toto.kdbx toto.key
Please provide the master password: *********
Couldn't load the file toto.kdbx: The database key appears invalid or else the database is corrupt.
```

Can you help ?

**Comment by alecsammon** [comment] 2016-04-16 16:18
Hi @sebma 

Sorry - I've not used this project for a long time!

It seams to be working fine for me. I'm using Ubuntu 14.04.4 LTS.

I tried with and without key files, with long and short passwords, including non ascii passwords.

Couple of thinks I can suggest.
1. Try resaving the original file without the key, then see if you can open it.
2. There has been a new version of kpcli published - I've updated it in this repo - now at v3.0 - I had to install the following additional dependency:  `sudo apt-get install libclone-perl`

Hope this helps

**Comment by sebma** [comment] 2016-04-16 16:32
Hi,

How do I resave "the original file without the key" with KeepassX or Keepass2 ?

**Comment by alecsammon** [comment] 2016-04-16 16:36
I use KeepassX - you can change the password and keyfile here:
<img width="576" alt="screen shot 2016-04-16 at 17 34 25" src="https://cloud.githubusercontent.com/assets/304636/14582329/a19dd0a6-03f9-11e6-8556-573c5f9bf160.png">

**Comment by sebma** [comment] 2016-04-16 16:44
This window allows me only to create a new key but not to delete the original key.

I'd like to share my screenshot on https://cloud.githubusercontent.com but I don't know how to do that :)

**Comment by sebma** [comment] 2016-04-16 16:58
Found it :)

![seb - keepassx_003](https://cloud.githubusercontent.com/assets/4569306/14582436/1d3f720e-0405-11e6-958b-7c9aee7290db.png)

**Comment by alecsammon** [comment] 2016-04-16 18:23
Can you not just uncheck the "Key file" checkbox?

**Comment by sebma** [comment] 2016-04-16 18:51
I feel kinda stupid :)

**Comment by alecsammon** [comment] 2016-04-16 18:52
glad to help ;)

**Comment by sebma** [comment] 2016-04-16 19:00
Still kpcli asks for a password when there's no password on my kdbx.

After setting a new password it works.

But after adding a keyfile, it does not work :(

```
kpcli:/> open toto.kdbx toto.key
Please provide the master password: *************************
Couldn't load the file toto.kdbx: The database key appears invalid or else the database is corrupt.
```

It's a shame because your application is the only one that supports, in console mode, Keepass2 databases.

Is there a verbose or debug mode to help ?

**Comment by alecsammon** [comment] 2016-04-18 08:20
It's not my library - the project is here: https://sourceforge.net/projects/kpcli/

It was dead when was looking at it a while back, and having it available via git helped for some of my workflows.

I think your best bet is to go to sourcefuse and look for help there.

Sorry

**Comment by sebma** [comment] 2016-04-18 18:03
Hi, the pb. is that the last account I created on sourceforge didn't allow me to raise any ticket.

I don't know why.

I'm creating a new one, hope it works this time.

**Comment by sebma** [comment] 2016-04-18 18:14
BTW, is there a linux command to download the source on sourceforge the way `git` does ?

**Comment by sebma** [comment] 2016-04-18 18:22
I have deleted my key file and created a new one with `kpcli export`

It seems that the new key file format is not a XML file (like my previous key file).

That's maybe why it didn't work.

**Comment by sebma** [comment] 2016-04-18 18:25
BTW, can you include the `kpcli` manpage (it contains the changelog) in your GIT, here is the command I found in the debian rules :

`pod2man --name KPCLI ./pl/kpcli.pl ./src/kpcli/kpcli.1`

**Comment by rogeruiz** [comment] 2016-10-16 02:51
Seems like this is most likely related to a formatting issue in the API for `FILE::KeePass` according to [this bug](https://sourceforge.net/p/kpcli/bugs/16/) filed and considered a `wontfix`. ~~I believe, creating a KeyFile from within `kpcli` fixes this, but I haven't done any testing _yet_ on this.~~ Whoops. Thanks @sebma, looks like you figured this out. Hopefully the sourceforge link helps with some information of what the bug is related to.

**Comment by rogeruiz** [comment] 2016-10-16 03:36
Yup. Steps to reproduce a fix for this is to do the following.

``` shell
$ kpcli
$kpcli> export <file.kdbx>
# follow the prompts and overwrite your kdbx file
# ensure you can log in to this new kdbx file without a key file
# delete the old key file
$kpcli> saveas <file.kdbx> <file.key>
# overwrite
# type in master password
# generate the new key file.
```

At this point you should be able to use either `kpcli` or the GUI. Thankfully 🙌 

The stark differences in the keyfiles are that the one generated by the GUI is XML and the other is just a single line. The following are example output of decommissioned key files.

**GUI generated**

``` shell
$ cat gui-generated-file.key
<?xml version="1.0" encoding="utf-8"?><KeyFile><Meta><Version>1.00</Version></Meta><Key><Data>HlT74cdlAa4hZXDh9E2c8AfLAajajJQM1K0OLjdeuA0=</Data></Key></KeyFile>
```

**kpcli generated**

``` shell
$ cat kpcli-generated-file.key
Wz4A&SqC67rqdZsVNKClfx3Yr#iuP=D*#)ZPc$mZq#e(U+$vtB5Iy^S_DQOMEW1RX*3PDYkDBU(T63(4_cK6R1Vd+7hU$bHoT6at=2f$jS@wi_VlIQjjEBWnQVAUW+Zgb_0bMRwo#v%3$ycXlDe4yq9XXy$27%w_L6fCA*2iLEM^93RLgNmq+c$R^@UAfXWbT*87d4z#LzmZvTkcu=o=OT89ZpHwOnCoElw4w85)+uTY%a@$n2jY^4c2w0Nap&*w1M=tDeHpQ1DFWxDqgqf*VBEt33GV^(Qy=BAKI_)G(czggD!$3UnZ%n81vD6$+a%5MSOuxUnVH!C5pZ*Ma%dDqr9VXZ3!@0Kf*$csfoBSK_!MHR(n^r5uM1(nlwawcK$5xY)U9lOHSkD_^bjVm&qs=Q2+uN(J60r_#@xZ%A4#Q#D&^OA6u*rvIPCEnbU3%Cs9#yBImfsy^HFwJ2WrHdDDQt^jGzf$KNZ^99CWyymd0l0*Sbu9u439N^wscyh)KYed+f$FAR_%IQ0MTRo0MFT)_JZkikjcWCFr(yGQ(&0Gtj1&kViC7sr_=sehI2bdyvbOBPLY$z$M0DExJ65I(2mbwAHUGE^lygoQi87P2OoXgY9J04H#4EZE%)mcCJqJw2et(%0Q*(vX=^0sEfGB(5T*mcpVRX1WuV1N_*8TABTwEy+_Pqh5dDHb%YarO81@+%(^G^sMc*aTW68yT7a$2L%8M^cCl4xb8Dvw55vWnL_G&2Dt4(91$8kk)n)SNFl^FF9F&=4^^05ihTfWdcDCT8f$cEvT_NQ0g8Xjyh)c3aRYHLHNK6bJiN!fymD_ncdIBlIuZP!#(kS!q=feD9hJNCH4U9!$B$gq)@by1e$SxVxMM^&jgg)hP$9IrdSH$^3kM3lcNa$HqYK$edaN9VhPlF3Q8tDetiWxKdmmlIsjUPnC#fRUkTbc3GTd7zjjxgHlLp5p+Z+S^LjqqLdWaC)z8sIcRz$8H9*Iw_UM6gkG#t2qi4nmP&O6x7s&l%5z8Bt6IS=cO%(9m$prxFW7tNp+y14f+M4Db%#a_VSf2TfUCdmjaQ)^ydKmAu6rN305dN2bf!6%A&!lM=43UkgAQKoly9&d4_GOhtlMl3*_VNS*Jz9sC%d4%l%8zqi_T#zZz*cA*soQcS@^TkfWnEoo5v&C%N!@(%Uai&9&HxyT*NSHt2xu!XTNP^UP6b%_40=#ysmFoyRhsE+EcYeT#aHeSx#AqvcTN^9Ka9mU3h_o8(!_J!%7E=i)V&ANa0Y6N)A74EtsyDEkTT5P&GzPbEPsk05AB36owRfyKa6H+v+ouZg5WlostMZcHSIWZT9rK35_L1H9J$B#ds3EHeXws=@J0*VIJStSlGKFu%B@l6pb*+TOqcY2^BWDQXpXClXu8Hv!c$sOwnwhuZmhk8vYfm64)i86FGR+8DMHla*0_UhzV+2!mLSeUrznSB@ji%aGRjzF40qZWA2cbE1qGiVx_qY@M4Hmgdk5F$BmZ&!zWdqxtGz*Olb2BXg0IO)Wl1+9V(Qc3V7T+0%TXu1PoK*y#Ci7Rm^M*ig1F3uSx*2er_cl&Ubc&F%6!n+Kpv^V8&G5Pn5th%Li7Crk#do1ZA*sTRdcK_M3FTUGLaes0dmxd$=D28r+_!f0=ba#iTJTuwn+sUBNI18pZP*7h^WtiuuCancni9OWZlAI0GKj6_mq1dja80zZWd4&**&wT=b_Yx7SGtBl+ER0qvBr3M$z*J5z=o!Dcl9Pj@0$=eqD8&MiC^@POvIrSqDqaQF=p@#6##kt*VzK@&S$x=4hFb&YE&C5Wk$46VfzT0omf1Twx@#718UWAC9s7fRr0T7Pwe@)nSVVxSEqx*BFuECq6=B+eeIiOt#tHE#!1X6y=w)EKRSaL!dLGeh!+&_M^swx0rX)JYVa$RAyIG@jhR4F3a2UNgRvjJ=b#DZyKuCanf0Tz(pgdm@_D_^w9)W!_IWkNN)9VX+BsX*KLSM$TEjUUnc8z5AR^Yiim&KXh)_oM+Hdwn$U9Mq+59+&Ku)4ktlE#b=O@4tUy4jz0v6iuUEJ
```

Hope this fix helps anyone searching for this issue. I'm also comfortable submitting a PR to the readme file which documents the above.

**Closed as completed** 2017-02-08 13:05 UTC

**Comment by sebma** [comment] 2017-02-08 13:32
@rogeruiz You are right, it is a File::Keepass issue : [‪Bug #97055 for File-KeePass: Does not accept XML key file](https://rt.cpan.org/Public/Bug/Display.html?id=97055)

**Comment by patrickdeelman** [comment] 2017-10-26 09:55
Since the kpcli package has few to none updates (last update over a year ago) i would recommend using keepass under mono.
As far as the CLI-only part of this, I can confirm it works without install X. To interact with the database using the cli, also download the KPScript plugin.

confirmed on Ubuntu 16.04: apt install mono-devel keepass2 and download/extract the kpscript utility into the /usr/lib/keepass2 folder.

**Comment by sebma** [comment] 2021-08-14 10:46
@rogeruiz Hi, "build me" :smile:
Is this related : https://github.com/tribut/kpcli#version-4-of-the-kdbx-file-format-is-unsupported ?

**Comment by rogeruiz** [comment] 2021-08-14 15:15
Hey @sebma I don't think it's related to the last link you posted. That link seems to be an incompatibility of the encryption algorithms. The original issue from 5 years ago is that the KeyPass GUI key is generated as XML but the KeyPass CLI expects it to be just a file. The fix is to take the hash out of the XML file and just put it in a file on its own line. Look at my previous comment and you'll see that the hash for my key is the same as the hash value inside the XML markup.

**Comment by sebma** [comment] 2021-08-14 21:14
@rogeruiz Oh I see. Thanks for this precision.
